name: 'Publish Code Page to Quickbase'
description: 'Publish a code page to a Quickbase realm'
author: 'Erik Azevedo'
inputs:
  realm:
    description: 'The Quickbase realm, i.e. realm.quickbase.com'
    required: true
  dbid:
    description: 'The main dbid, or appid, of the realm'
    required: true
  usertoken:
    description: 'A valid usertoken with rights to create a code page'
    required: true
  path:
    description: 'The repository filepath of the code page'
    required: true
  filename:
    description: 'The filename of the code page, with extension'
    required: true
  pageid:
    description: 'The page ID of the code page'
    required: false
    default: 0
runs:
  using: "composite"
  steps:
    - name: Deploy Update To Quickbase
      shell: bash
      run: |
        echo "<qdbapi><pageid>${{ inputs.pageid }}</pageid><pagetype>1</pagetype><pagebody><![CDATA[" > output
        cat ${{ inputs.path }}/${{ inputs.filename }} >> output
        echo "]]></pagebody><usertoken>${{ inputs.usertoken }}</usertoken></qdbapi>" >> output
        curl -X POST \
          -H "Content-Type: application/xml" \
          -H "QUICKBASE-ACTION: API_AddReplaceDBPage" \
          --data-binary "@output" \
          https://${{ inputs.realm }}/db/${{ inputs.dbid }}
